spin_manifest_version = 2

[application]
name = "my-leptos-app"
version = "0.1.0"
authors = ["J <2742259+javdl@users.noreply.github.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "my-leptos-app"

[component.my-leptos-app]
source = "target/wasm32-wasip1/release/my_leptos_app.wasm"
allowed_outbound_hosts = []
key_value_stores = ["default"]
[component.my-leptos-app.build]
command = "cargo leptos build --release && LEPTOS_OUTPUT_NAME=my_leptos_app cargo build --lib --target wasm32-wasip1 --release --no-default-features --features ssr"
watch = ["src/**/*.rs", "Cargo.toml"]

[[trigger.http]]
route = "/pkg/..."
component = "my-leptos-app-pkg"

[component.my-leptos-app-pkg]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.1.0/spin_static_fs.wasm", digest = "sha256:96c76d9af86420b39eb6cd7be5550e3cb5d4cc4de572ce0fd1f6a29471536cb4" }
files = [{ source = "target/site/pkg", destination = "/" }]

[[trigger.http]]
route = "/images/..."
component = "static-files"

[component.static-files]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.1.0/spin_static_fs.wasm", digest = "sha256:96c76d9af86420b39eb6cd7be5550e3cb5d4cc4de572ce0fd1f6a29471536cb4" }
files = [{ source = "public", destination = "/" }]
